---
title: "Getting Started with DoubleML"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started with DoubleML}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = FALSE)
```


## Getting started with DoubleML


### Installation 

The `DoubleML` package for R can be downloaded using (R package `devtools` is required)

```{r, eval = FALSE}
devtools::install_github("MartinSpindler/dml", subdir = "/packages/R/dml")
```

Load the package after completed installation. 

```{r}
library(DoubleML)
```

```{r}
example(DoubleML)
```


### Quickstart Example

Load the preprocessed data object for the quickstart example.  
```{r}
DoubleMLData_401k = data("DoubleMLData_401k")
print(DoubleMLData_401k)
```


Select a learner as provided by the `mlr3` and `mlr3learners` packages. 

```{r}
learner = "regr.ranger"
ml_learners_401k = list("mlmethod_m" = learner, "mlmethod_g" = learner)
```


```{r}
PLR_401k = DoubleMLPLR$new(DoubleMLData_401k,  
                            n_folds = 2,
                            ml_learners = ml_learners_401k, 
                            dml_procedure = "dml2", 
                            inf_model = "DML2018")
PLR_401k$fit()
PLR_401k$summary()
```




