name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - PhilippBach

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and concise discription of the bug.
    validations:
      required: true
  - type: textarea
    id: mwe
    attributes:
      label: Minimum reproducible code snippet
      description: |
        Please provide a short reproducible code snippet. Example:

        ```R
        library(DoubleML)
        library(mlr3)
        library(mlr3learners)
        library(data.table)
        set.seed(2)
        ml_g = lrn("regr.ranger", num.trees = 10, max.depth = 2)
        ml_m = ml_g$clone()
        obj_dml_data = make_plr_CCDDHNR2018(alpha = 0.5)
        dml_plr_obj = DoubleMLPLR$new(obj_dml_data, ml_g, ml_m)
        dml_plr_obj$fit()
        dml_plr_obj$summary()
        ```
      placeholder: |

        ```R
        Sample code here
        ```
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: |
        State the result you would have expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: |
        State the result you get (for example an exception including the full traceback)
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Please run the following code and copy-paste the result

        ```R
        sessionInfo()
        packageVersion('DoubleML')
        packageVersion('mlr3')
        ```
    validations:
      required: true